name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install https://github.com/wmo-im/cap-validator/archive/main.zip
    - name: run tests ⚙️
      run: |
        pytest
    - name: run flake8 ⚙️
      run: |
        flake8
